version: '3.8'
services:
  redis:
    image: redis
    restart: always   
  server:
    container_name: server-puppeteer-ci
    build:
      context: .
      dockerfile: Dockerfile.ci
    environment:
      - NODE_ENV=ci
    depends_on:
      - redis    