version: '3.8'
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis:/data
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=dev
    ports:
      - 3001:3001
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    depends_on:
      - redis
volumes:
  redis: